import bcrypt from 'bcryptjs';

// Pre-hashed password for: "studentPass2026", "wardenPass2026", "techPass2026"
const studentHashedPass = bcrypt.hashSync('studentPass2026', 10);
const wardenHashedPass = bcrypt.hashSync('wardenPass2026', 10);
const techHashedPass = bcrypt.hashSync('techPass2026', 10);

export let inMemoryUsers = [
  {
    _id: 'usr_student_01',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@campus.edu',
    studentOrStaffId: '2023CSB1042',
    password: studentHashedPass,
    role: 'student',
    hostel: 'Boys Hostel 2 (Satpura)',
    roomNumber: 'Room 302',
    phone: '+91 98765 43210',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_warden_01',
    name: 'Dr. K. Mehta',
    email: 'warden.satpura@campus.edu',
    studentOrStaffId: 'FAC-WAR-09',
    password: wardenHashedPass,
    role: 'warden',
    hostel: 'Boys Hostel 2 (Satpura)',
    roomNumber: 'Warden Quarters Block A',
    phone: '+91 98765 11111',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_tech_01',
    name: 'Ramesh Kumar',
    email: 'ramesh.plumber@campus.edu',
    studentOrStaffId: 'STAFF-PLUMB-04',
    password: techHashedPass,
    role: 'technician',
    hostel: 'Central Maintenance Yard',
    roomNumber: 'Workshop 2',
    phone: '+91 98765 22222',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_admin_01',
    name: 'Chief Admin (Dean Student Affairs)',
    email: 'admin.affairs@campus.edu',
    studentOrStaffId: 'ADMIN-DSA-01',
    password: wardenHashedPass,
    role: 'admin',
    hostel: 'Admin Block B',
    roomNumber: 'Room 204',
    phone: '+91 98765 33333',
    createdAt: new Date().toISOString(),
  },
];

export let inMemoryComplaints = [
  {
    _id: 'comp_00124',
    complaintId: 'CF-2026-00124',
    title: 'Low water pressure & tap leakage in 3rd floor washroom',
    category: 'Water Supply',
    categorySlug: 'water-supply',
    hostel: 'Boys Hostel 2 (Satpura)',
    roomNumber: 'Wing B, Washroom 302',
    studentName: 'Aarav Sharma',
    studentId: '2023CSB1042',
    priority: 'High',
    status: 'In Progress',
    currentStepIndex: 3,
    description: 'Main tap in bathroom stall 2 has a continuous spray leakage causing slippery floor. Pressure across 3rd floor taps is severely reduced since morning.',
    imageUrl: '',
    proofImageUrl: '',
    assignedTo: 'Ramesh Kumar (Chief Plumber)',
    expectedResolution: 'Today, 06:00 PM',
    upvotes: 18,
    upvotedBy: ['2023CSB1042', '2023CSB1045'],
    verificationStatus: 'Pending',
    createdAt: '2026-10-05 09:30 AM',
    updatedAt: '2026-10-06 02:15 PM',
    timeline: [
      { step: 'Reported', date: 'Oct 05, 09:30 AM', note: 'Ticket logged by Aarav S.', updatedBy: 'Aarav Sharma' },
      { step: 'Under Review', date: 'Oct 05, 11:00 AM', note: 'Verified by Hostel Warden Dr. K. Mehta', updatedBy: 'Dr. K. Mehta' },
      { step: 'Assigned', date: 'Oct 05, 02:30 PM', note: 'Assigned to Central Campus Plumbing Team', updatedBy: 'Dr. K. Mehta' },
      { step: 'In Progress', date: 'Oct 06, 10:00 AM', note: 'Replacement valve parts dispatched to Wing B', updatedBy: 'Ramesh Kumar' },
      { step: 'Resolved', date: 'Pending', note: 'Final inspection remaining', updatedBy: 'System' }
    ]
  },
  {
    _id: 'comp_00125',
    complaintId: 'CF-2026-00125',
    title: 'Wi-Fi access point in corridor 4 offline since thunderstorm',
    category: 'Wi-Fi',
    categorySlug: 'wifi',
    hostel: 'Girls Hostel 1 (Aravali)',
    roomNumber: '4th Floor West Wing',
    studentName: 'Priya Patel',
    studentId: '2024ECE1108',
    priority: 'Medium',
    status: 'Assigned',
    currentStepIndex: 2,
    description: 'The Cisco AP LED is blinking amber and not broadcasting CampusSecure SSID. Over 40 students cannot access lecture portals.',
    imageUrl: '',
    proofImageUrl: '',
    assignedTo: 'Campus IT Network Cell (Eng. Vikram Singh)',
    expectedResolution: 'Oct 07, 12:00 PM',
    upvotes: 24,
    upvotedBy: ['2024ECE1108'],
    verificationStatus: 'Pending',
    createdAt: '2026-10-05 06:20 PM',
    updatedAt: '2026-10-06 10:45 AM',
    timeline: [
      { step: 'Reported', date: 'Oct 05, 06:20 PM', note: 'Complaint logged via student portal', updatedBy: 'Priya Patel' },
      { step: 'Under Review', date: 'Oct 05, 08:00 PM', note: 'Warden forwarded to Network Administrator', updatedBy: 'Warden Desk' },
      { step: 'Assigned', date: 'Oct 06, 10:45 AM', note: 'IT technician scheduled for site diagnosis', updatedBy: 'Network Admin' },
      { step: 'In Progress', date: 'Pending', note: 'Corridor switch diagnostic pending', updatedBy: 'System' },
      { step: 'Resolved', date: 'Pending', note: 'Awaiting verification', updatedBy: 'System' }
    ]
  },
  {
    _id: 'comp_00126',
    complaintId: 'CF-2026-00126',
    title: 'Ceiling fan regulator sparking and producing burning smell',
    category: 'Electricity',
    categorySlug: 'electricity',
    hostel: 'Boys Hostel 1 (Vindhya)',
    roomNumber: 'Room 214',
    studentName: 'Rohan Verma',
    studentId: '2022MEB1075',
    priority: 'Urgent',
    status: 'Resolved',
    currentStepIndex: 4,
    description: 'Switch box had sparks when turned to speed 3. Kept main switch off for safety.',
    imageUrl: '',
    proofImageUrl: '',
    assignedTo: 'Manoj Tiwari (Campus Electrician)',
    expectedResolution: 'Resolved on Oct 05',
    upvotes: 31,
    upvotedBy: ['2022MEB1075'],
    verificationStatus: 'Verified',
    createdAt: '2026-10-04 03:10 PM',
    updatedAt: '2026-10-05 11:30 AM',
    timeline: [
      { step: 'Reported', date: 'Oct 04, 03:10 PM', note: 'Urgent electrical report received', updatedBy: 'Rohan Verma' },
      { step: 'Under Review', date: 'Oct 04, 03:20 PM', note: 'Emergency flag raised by Caretaker', updatedBy: 'Caretaker' },
      { step: 'Assigned', date: 'Oct 04, 03:45 PM', note: 'Electrician dispatched immediately', updatedBy: 'Warden' },
      { step: 'In Progress', date: 'Oct 04, 04:15 PM', note: 'Regulator and wiring harness replaced', updatedBy: 'Manoj Tiwari' },
      { step: 'Resolved', date: 'Oct 05, 11:30 AM', note: 'Tested safely and verified by student Rohan', updatedBy: 'Rohan Verma' }
    ]
  },
  {
    _id: 'comp_00127',
    complaintId: 'CF-2026-00127',
    title: 'Mess Hall drinking water UV purifier service overdue',
    category: 'Mess Services',
    categorySlug: 'mess-services',
    hostel: 'Central Dining Hall',
    roomNumber: 'Block A, Ground Floor',
    studentName: 'Ananya Deshmukh',
    studentId: '2023CSB1190',
    priority: 'Medium',
    status: 'Under Review',
    currentStepIndex: 1,
    description: 'Filter indicator light is red, students noticing slight chlorine taste. Kindly service RO membrane.',
    imageUrl: '',
    proofImageUrl: '',
    assignedTo: 'Mess Welfare Committee',
    expectedResolution: 'Oct 08, 05:00 PM',
    upvotes: 42,
    upvotedBy: ['2023CSB1190'],
    verificationStatus: 'Pending',
    createdAt: '2026-10-06 08:45 AM',
    updatedAt: '2026-10-06 09:15 AM',
    timeline: [
      { step: 'Reported', date: 'Oct 06, 08:45 AM', note: 'Logged by Dining Council Rep', updatedBy: 'Ananya Deshmukh' },
      { step: 'Under Review', date: 'Oct 06, 09:15 AM', note: 'Acknowledged by Food Quality Officer', updatedBy: 'Food Quality Officer' },
      { step: 'Assigned', date: 'Pending', note: 'Awaiting vendor technician slot', updatedBy: 'System' },
      { step: 'In Progress', date: 'Pending', note: 'Filter cartridge replacement', updatedBy: 'System' },
      { step: 'Resolved', date: 'Pending', note: 'Water purity test sign-off', updatedBy: 'System' }
    ]
  },
  {
    _id: 'comp_00128',
    complaintId: 'CF-2026-00128',
    title: 'Door lock cylinder jammed, key difficult to turn',
    category: 'Room Maintenance',
    categorySlug: 'room-maintenance',
    hostel: 'Girls Hostel 2 (Nilgiri)',
    roomNumber: 'Room 108',
    studentName: 'Sneha Kapoor',
    studentId: '2024CHB1020',
    priority: 'Low',
    status: 'Reported',
    currentStepIndex: 0,
    description: 'Mortise lock is sticky and gets stuck when locking from outside.',
    imageUrl: '',
    proofImageUrl: '',
    assignedTo: 'Hostel Caretaker',
    expectedResolution: 'Oct 08, 02:00 PM',
    upvotes: 5,
    upvotedBy: ['2024CHB1020'],
    verificationStatus: 'Pending',
    createdAt: '2026-10-06 01:20 PM',
    updatedAt: '2026-10-06 01:20 PM',
    timeline: [
      { step: 'Reported', date: 'Oct 06, 01:20 PM', note: 'Submitted via CampusFix web app', updatedBy: 'Sneha Kapoor' },
      { step: 'Under Review', date: 'Pending', note: 'Warden queue', updatedBy: 'System' },
      { step: 'Assigned', date: 'Pending', note: 'Carpentry crew queue', updatedBy: 'System' },
      { step: 'In Progress', date: 'Pending', note: 'Lock cylinder lubricate / replacement', updatedBy: 'System' },
      { step: 'Resolved', date: 'Pending', note: 'Completion', updatedBy: 'System' }
    ]
  }
];

export let inMemoryInquiries = [];
